### ISSUE TITLE
Hotspot user returns invalid credentials

### ISSUE THREAD

**Issue by cinghialino** [ufozone/ha-unifi-voucher#125]
i can't use a "Hotspot Manager" credentials when setting up the integration, it only works with a Administrator role.

**Comment by ufozone** [comment]
I have tried it with a local user with hotspot manager rights and it works.
We need more information:
- Controller hosting type
- Controller network version
- HA integration logs
- ...

**Comment by cinghialino** [comment]
Controller hosting type: Docker container, jacobalberty/unifi:latest
Controller network version: 8.4.59
HA integration logs: `Login failed '{'meta': {'rc': 'error', 'msg': 'api.err.Invalid'}, 'data': []}'`

again, the problem does not appear (and everything works as intended) when using an Administrator account

**Comment by ufozone** [comment]
The error message comes directly from the controller and not from the integration. A login with an incorrect password is recognized in this way.

With the following settings, I can create a local user with which the integration can log in:
![grafik](https://github.com/user-attachments/assets/ebaef754-00bf-480d-a75a-f9e02ee54a76)

If you can use an admin user, then this might be the right way for you. Your problem is not due to the integration - then a different error message would appear in the logs.

**Comment by cinghialino** [comment]
got it. Thanks for the explanation. Curiously, when I am setting up an user as a hotspot manager, I do not get the same UI as you. Check this out:
<img width="403" alt="Screenshot 2024-09-15 at 06 47 52" src="https://github.com/user-attachments/assets/854ed682-8566-47bb-9b68-c0099dbcaafa">

**Comment by cinghialino** [comment]
also check this
<img width="396" alt="Screenshot 2024-09-15 at 06 51 39" src="https://github.com/user-attachments/assets/39be52d5-b812-4df1-a5b6-93ca7e46c0d8">

**Comment by ufozone** [comment]
> got it. Thanks for the explanation. Curiously, when I am setting up an user as a hotspot manager, I do not get the same UI as you. Check this out: <img alt="Screenshot 2024-09-15 at 06 47 52" width="403" src="https://private-user-images.githubusercontent.com/11861982/367576093-854ed682-8566-47bb-9b68-c0099dbcaafa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDA4OTksIm5iZiI6MTcyNjQwMDU5OSwicGF0aCI6Ii8xMTg2MTk4Mi8zNjc1NzYwOTMtODU0ZWQ2ODItODU2Ni00N2JiLTliNjgtYzAwOTlkYmNhYWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDExNDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YTZiNWQyYWM1NWU2MzU4NGU2NjY0OTU1YjVmN2JmNzZjOWFkN2ZhMmEwMjU4NDU2ZjFlODU4MThjMGUxNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RbCXTqpZhjWsVQoV4DxjuXjevuEFy0FYn3uNlJ-1O-8">

I don't know the docker version of the controller. But it doesn't actually look that wrong. The integration uses the Unifi library [https://github.com/Kane610/aiounifi](Kane610/aiounifi). It is the same one that is used by the [https://www.home-assistant.io/integrations/unifi/](UniFi Network Core Integration). Try logging into this once with the new user. If this does not work either, it is due to the Docker environment.

> also check this <img alt="Screenshot 2024-09-15 at 06 51 39" width="396" src="https://private-user-images.githubusercontent.com/11861982/367576296-39be52d5-b812-4df1-a5b6-93ca7e46c0d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDA4OTksIm5iZiI6MTcyNjQwMDU5OSwicGF0aCI6Ii8xMTg2MTk4Mi8zNjc1NzYyOTYtMzliZTUyZDUtYjgxMi00ZGYxLWE1YjYtOTNjYTdlNDZjMGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDExNDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YmUxYzZjZTJkNWNiMmQ2NDM5ZGU0MjU3YmI3NGZkMmU5NmYyOWM2YTdlZDZkNTE4ZmU0YmMwYWVlYjdiYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y3nw6N-oRUNK35wVcnK3rz1-SY_5XByZZldYKTOm1Aw">

I have fixed the typo.

**Comment by cinghialino** [comment]
just discovered it's a networking issue. The controller in docker uses the container internal ip address (172.17.2.33) that creates the problem and doesn't allow me to see the hotspot manager UI, therefore denying the credentials. This doesn't happen when changing the Hotspot URL IP to the one of the machine itself.
I'm currently trying to fix it using macvlan.

**Comment by cinghialino** [comment]
not solved. I don't understand it as I can login in the hotspot manager interface no problem, but when I use the same information in the integration, it doesn't work. it's not a networking problem.

**Comment by ufozone** [comment]
> I don't know the docker version of the controller. But it doesn't actually look that wrong. The integration uses the Unifi library [https://github.com/Kane610/aiounifi](Kane610/aiounifi). It is the same one that is used by the [https://www.home-assistant.io/integrations/unifi/](UniFi Network Core Integration). Try logging into this once with the new user. If this does not work either, it is due to the Docker environment.

can you log into the unifi network integration with this username or not? if not, then it's not the integration but the docker setup

**Comment by cinghialino** [comment]
I can only setup the integration with my Administrator user (which is also remote accessible), but NOT with the hotspot manager user.

**Comment by ufozone** [comment]
Yes, I understood that. Then it doesn't seem to work with your Docker setup. Sorry, I can't help you.

**Comment by cinghialino** [comment]
that's one way to "solve" it. thanks! take care.

**Comment by ufozone** [comment]
Sure. I have two other ideas to solve it:
1. create a fork and analyze your issue yourself. If you actually find a bug in the integration, then fix it and create a pull request. That way you are doing something for the community.
2. create a proper bug report with all the information we need. Don't let people pull everything out of your nose and help to find the problem. This would also help the community.

But what are you doing? A bug report with only "does not work" description, you only provide half of the information I ask you for, and incomplete information at all. Then you get snotty. How the hell are we supposed to help you like that?

Tens of people, including me, have successfully run the integrations with an only hotspot manager user. Your problem is not reproducible, so what should I do without more information????

**Comment by cinghialino** [comment]
I got snarky when you dismissed it with closing the ticket and telling me "I can't help you". Have you thought for a moment that not everyone has the same knowledge as you? 

what do you need? please be specific.

**Comment by ufozone** [comment]
Sure, nobody has the same knowledge about the integration as I in the moment.

I'll make it clear again:
This one log entry you copied in here comes from your controller. Not from HA integration.
If it works with the admin and not with the other user, it seems to be due to your controller. Not the HA integration.
And without further logs and diagnostic information from the HA integration, there is simply nothing I can do.

And since you don't provide any further information and it looks like it's just your controller, this "issue" is solved here. Until you provide more information that tells us otherwise.

The read me explains how to activate debug mode. Do that. Try it again and paste the logs here (retain passwords first).

It is possible that it does not work due to the docker setup. To find out, you should try it with your hotspot user and the core integration "UniFi Network". Activate the logs there too and see what it says. If that doesn't work either, then it's due to the controller in the docker.

**Comment by ufozone** [comment]
@cinghialino, can you provide anything else here? Or is the issue closed and you are using the Admin user?

**Comment by cinghialino** [comment]
Hey ufozone, haven't got the time yet. I'll provide what you need tomorrow to troubleshoot. Thanks

**Comment by ufozone** [comment]
I have installed the Docker image `jacobalberty/unifi` and can reproduce your issue. Login with admin user works, login with hotspot manager does not work. Detailed log:
```log
2024-09-20 11:33:02.725 DEBUG (MainThread) [aiounifi.interfaces.connectivity] sending (to https://10.0.99.133:32770) get, None, False
2024-09-20 11:33:02.796 DEBUG (MainThread) [aiounifi.interfaces.connectivity] received (from https://10.0.99.133:32770) 302 application/octet-stream <ClientResponse(https://10.0.99.133:32770) [302 None]>
<CIMultiDictProxy('Location': '/manage', 'Content-Length': '0', 'Date': 'Fri, 20 Sep 2024 11:33:02 GMT')>

2024-09-20 11:33:02.796 DEBUG (MainThread) [aiounifi.interfaces.connectivity] data (from https://10.0.99.133:32770) b''
2024-09-20 11:33:02.796 DEBUG (MainThread) [aiounifi.interfaces.connectivity] Talking to UniFi OS device: False
2024-09-20 11:33:02.797 DEBUG (MainThread) [aiounifi.interfaces.connectivity] sending (to https://10.0.99.133:32770/api/login) post, {'username': 'test', 'password': 'test', 'rememberMe': True}, True
2024-09-20 11:33:03.587 DEBUG (MainThread) [aiounifi.interfaces.connectivity] received (from https://10.0.99.133:32770/api/login) 400 application/json <ClientResponse(https://10.0.99.133:32770/api/login) [400 None]>
<CIMultiDictProxy('Vary': 'Origin', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '57', 'Date': 'Fri, 20 Sep 2024 11:33:02 GMT', 'Connection': 'close')>

2024-09-20 11:33:03.587 DEBUG (MainThread) [aiounifi.interfaces.connectivity] data (from https://10.0.99.133:32770/api/login) b'{"meta":{"rc":"error","msg":"api.err.Invalid"},"data":[]}'
2024-09-20 11:33:03.587 ERROR (MainThread) [aiounifi.interfaces.connectivity] Login failed '{'meta': {'rc': 'error', 'msg': 'api.err.Invalid'}, 'data': []}'
2024-09-20 11:33:03.587 WARNING (MainThread) [custom_components.unifi_voucher] Connected to UniFi Network at 10.0.99.133 but login required: 
```

The UniFi OS user management is not fully implemented in this Docker image.  Also the hotspot manager implementation does not correspond to the Unifi OS on a Cloud Key or UDM. It is also not an official application of Ubiquiti UniFi.

Since my integration uses the library `aiounifi` to connect to the UniFi Controller, there is unfortunately nothing I can do. You now have three options:
1. Use the integration with the admin user.
2. Open an issue in the repository of the Docker image so that the user management is implemented exactly as in the UniFi OS.
3. Use an official CloudKey or a UDM.

In any case, there is nothing more we can do at this point. It has nothing to do with my integration.

**Comment by sir-Unknown** [comment]
The following seems to be working for logging in as a hotspot operator user:
  curl 'https://*.*.*.*:8443/api/login'  --data-raw '{"username":"hasshotspot","password":"**************","for_hotspot":true,"remember":false,"site_name":"default"}'  --insecure

Adding these operators should fix the login process:
"for_hotspot":true
"site_name":"default"

**Comment by ufozone** [comment]
Thanks for sharing. That looks possible. This would require creating a PR in the aiounifi library:
https://github.com/Kane610/aiounifi/

**Comment by sir-Unknown** [comment]
I forked aiounifi to give it a try, but I'll just have to see how far I come with my chatgpt assisted skills

**Comment by ufozone** [comment]
I clicked through the source code. I remember that I found it so difficult to understand the logic last time ...

But I think you need only `for_hotspot` attribute in the configuration, `site` is available:
https://github.com/sir-Unknown/aiounifi/blob/c00efa9d1f3ddc584089d9f7410aa591c88ee62e/aiounifi/models/configuration.py#L20
```python
    site: str = "default"
    for_hotspot: bool | None = None
```

In your part of the login, replace `site_name` with `site`, if I see it correctly:
https://github.com/sir-Unknown/aiounifi/blob/c00efa9d1f3ddc584089d9f7410aa591c88ee62e/aiounifi/interfaces/connectivity.py#L78
```python
        if hasattr(self.config, "site") and self.config.site is not None:
            auth["site_name"] = self.config.site
```

It may be that the JSON keys in Python cannot be used in this way and must be changed:
```python
auth["forHotspot"]
auth["siteName"]
```

If everything fits, then the call of the `Configuration`-model still needs to be adapted:
https://github.com/sir-Unknown/aiounifi/blob/patch-1/aiounifi/__main__.py
```python
async def unifi_controller(
    host: str,
    username: str,
    password: str,
    port: int,
    site: str,
    session: aiohttp.ClientSession,
    ssl_context: SSLContext | None = None,
    for_hotspot: bool | None = None, # New argument
) -> Controller | None:
    """Set up UniFi controller and verify credentials."""
    controller = Controller(
        Configuration(
            session,
            host,
            username=username,
            password=password,
            port=port,
            site=site,
            for_hotspot=for_hotspot, # New argument
            ssl_context=ssl_context if ssl_context is not None else False,
        )
    )
```

You can test like this:
1. Download the latest version of the integration
    https://github.com/ufozone/ha-unifi-voucher/releases/download/v1.4/unifi_voucher.zip

2. Search and replace the following strings in the source code of the integration
    `import aiounifi` => `import .aiounifi`
    `from aiounifi.` => `from .aiounifi.`
    
4. Copy your fork from `aiounifi` (full directory) into the directory `/custom_components/unifi_voucher/`

6. The integration will now use your version of `aiounifi`.

8. You can hardcode the new attribute into the login for now
    https://github.com/ufozone/ha-unifi-voucher/blob/main/custom_components/unifi_voucher/api.py#L71
    ```python
            Configuration(
                session,
                host=host,
                username=username,
                password=password,
                port=port,
                site=site_id,
                for_hotspot=True, # This is ne new line
                ssl_context=verify_ssl,
            )
    ```

9. If everything works and your PR is `aiounifi` is merged, we will integrate it into the integration.

**Comment by sir-Unknown** [comment]
NIce, thanks! I just tested it and it works!

I'll update the PR for aiounifi

**Comment by Kane610** [comment]
> I clicked through the source code. I remember that I found it so difficult to understand the logic last time ...

Do you have any suggestions to simplify the design?

**Comment by ufozone** [comment]
> Do you have any suggestions to simplify the design?

I think it's because of my incompetence: I'm not really familiar with the Python design pattern and best practices. To me, many AIO libraries seem very complex on the one hand, but insufficiently hardened against “shit inputs” on the other.

**Comment by Kane610** [comment]
> > Do you have any suggestions to simplify the design?
> 
> I think it's because of my incompetence: I'm not really familiar with the Python design pattern and best practices. To me, many AIO libraries seem very complex on the one hand, but insufficiently hardened against “shit inputs” on the other.

Allright! If you come to think of anything open an issue in the lib and we can talk.
