### ISSUE TITLE
[Bug] Entities are named after the hexadecimal configuration ID

### ISSUE THREAD

**Issue by cryptk** [ufozone/ha-unifi-voucher#160]
### Detailed description

Hello, all of the entities created by this integration have entity_ids with the hexadecimal configuration ID, for example the create voucher button, it's entity_id will be something like `button.abcd1234_create`. This makes it quite difficult to determine what this button belongs to and it's more typical to have the entity ids be something more like `button.device_name_entity_name`, so with that create button, something like `button.site_name_create_voucher`.

I think (but haven't tested to verify) that this is happening because of things like this: https://github.com/ufozone/ha-unifi-voucher/blob/main/custom_components/unifi_voucher/entity.py#L46 where you are providing the device name using the title of the config entry, which IIRC is the hexadecimal ID of the config entry. It would probably be better to have this name be some descriptive text.  I would recommend something like ${SITE_ID}_${WLAN_NAME} if a wlan name has been provided or ${SITE_ID} if no wlan name has been provided.

### What version of the integration has the issue?

v1.4

### What version of Home Assistant Core has the issue?

core-2024.12.1

### Which version of UniFi Network Application is running?

8.6.9

### Has UniFi Network Application been recently updated?

No

### What type of installation of UniFi Controller are you running?

Dream Machine

### Diagnostics information

[config_entry-unifi_voucher-01JERWTT6164Y5ZDCVZE9X37XW.json](https://github.com/user-attachments/files/18084631/config_entry-unifi_voucher-01JERWTT6164Y5ZDCVZE9X37XW.json)

**Comment by cryptk** [comment]
Looking into the code a bit, the issue is actually here https://github.com/ufozone/ha-unifi-voucher/blob/main/custom_components/unifi_voucher/entity.py#L41

You don't need to set the entity_id value like that, Home Assistant will auto generate an entity_id based on the entity type, device name and entity name for you. Using the auto-generated entity_ids will align better with what Home Assistant users expect, and it will allow the functionality to have the entities renamed when the device is renamed to work.

I tested removing that one line and I now get entity_ids like the following `button.${SITE_ID}_create_voucher`, which is much easier to understand what it is when reading it, for example, in an automation, as opposed to something like `button.abcde123_create` (what's it creating, what does it belong to, lots of questions arise when I read that entity_id outside of the context of the integration panel).

**Comment by ufozone** [comment]
Thank you for your detailed analysis.

You have correctly recognized where the entity_id is set. This was necessary because the auto-generated entity_id was causing problems. 

Unfortunately I can't reconstruct it anymore, because I came across it before version 0.1. Anyway, for the HA Config Enrty we need a unique ID in the UniFi universe to be able to identify the Config Entry again for updates and co. The string that seems cryptic to you is the Site ID returned by your UniFi Controller. Not pretty, but functional and more unique than the site or WiFi name.

There were problems with auto-generated entity_id, but not with a fixed one. Interestingly, you can now simply rename the entities according to your own wishes without getting problems. Is that perhaps a solution for you?

Due to the continuous awesome enhancements of Home Assistant, everything becomes more configurable via UI. Most users already no longer come into contact with the classic entity ids. Your suggestion - which I understand 100% from an IT nerd and Monk point of view - would bring any side effects or impacts into the project. Deal?
